name: CI & CD

on:
  push:
    tags:
      - '*'

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_RELEASE_BUILD: true
        with:
          gradle-version: 7.6
          arguments: clean test build publish --stacktrace
